In [30]:
import pandas as pd
iris_filename='C:\\Users\\la\\Desktop\\PythonDataScienceEssentialsSecondEdition_Code\\Chapter 2\\code\\datasets-uci-iris.csv'
iris=pd.read_csv(iris_filename, sep=',',decimal='.', header=None,
                      names=['sepal_length','sepal_width', 'petal_length','petal_width','target'])

In [5]:
iris_iterator=pd.read_csv(iris_filename, header=None, names=['c1','c2','c3','c4','c5'], iterator=True)
print(iris_iterator.get_chunk(10).shape)
print(iris_iterator.get_chunk(20).shape)
piece=iris_iterator.get_chunk(2) 
piece

(10, 5)
(20, 5)

     c1   c2   c3   c4           c5
30  4.8  3.1  1.6  0.2  Iris-setosa
31  5.4  3.4  1.5  0.4  Iris-setosa

In [8]:
import csv
with open(iris_filename, 'rt') as data_stream:
    for n,row in enumerate(csv.DictReader(data_stream, 
                fieldnames=['sepal_length','sepal_width', 'petal_length','petal_width','target'], dialect='excel')):
        if n==0:
            print(n,row)
        else:
            break

0 OrderedDict([('sepal_length', '5.1'), ('sepal_width', '3.5'), ('petal_length', '1.4'), ('petal_width', '0.2'), ('target', 'Iris-setosa')])

In [10]:
with open(iris_filename, 'rt') as data_stream:
    for n,row in enumerate(csv.reader(data_stream, dialect='excel')):
        if n==0:
            print(row)
        else:
            break

['5.1', '3.5', '1.4', '0.2', 'Iris-setosa']

In [17]:
def batch_read(filename, batch=5):
    with open(filename, 'rt') as data_stream:
        batch_output=list()
        for n, row in enumerate(csv.reader(data_stream,dialect='excel')):
            if n>0 and n%batch ==0:
                yield(np.array(batch_output))
                batch_output=list()
            batch_output.append(row)
        yield(np.array(batch_output))

In [19]:
import numpy as np
for batch_input in batch_read(iris_filename,batch=7):
    print(batch_input)

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']]
[['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']]
[['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']]
[['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['5.1' '3.3' '1.7' '0.5' 'Iris-setosa']
 ['4.8' '3.4' '1.9' '0.2' 'Iris-setosa']
 ['5.0' '3.0' '1.6' '0.2' 'Iris-setosa']
 ['5.0' '3.4' '1.6' '0.4' 'Iris-setosa']
 ['5.2' '3.5' '1.5' '0.2' 'Iris-setosa']]
[['5.2' '3.4' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.1' '1.6' '0.2' 'Iris-setosa']
 ['5.4' '3.4' '1.5' '0.4' 'Iris-setosa']
 ['5.2' '4.1' '1.5' '0.1' 'Iris-setosa']
 ['5.5' '4.2' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']]
[['5.0' '3.2' '1.2' '0.2' 'Iris-setosa']
 ['5.5' '3.5' '1.3' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['4.4' '3.0' '1.3' '0.2' 'Iris-setosa']
 ['5.1' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.5' '1.3' '0.3' 'Iris-setosa']
 ['4.5' '2.3' '1.3' '0.3' 'Iris-setosa']]
[['4.4' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['5.0' '3.5' '1.6' '0.6' 'Iris-setosa']
 ['5.1' '3.8' '1.9' '0.4' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.6' '0.2' 'Iris-setosa']
 ['4.6' '3.2' '1.4' '0.2' 'Iris-setosa']
 ['5.3' '3.7' '1.5' '0.2' 'Iris-setosa']]
[['5.0' '3.3' '1.4' '0.2' 'Iris-setosa']
 ['7.0' '3.2' '4.7' '1.4' 'Iris-versicolor']
 ['6.4' '3.2' '4.5' '1.5' 'Iris-versicolor']
 ['6.9' '3.1' '4.9' '1.5' 'Iris-versicolor']
 ['5.5' '2.3' '4.0' '1.3' 'Iris-versicolor']
 ['6.5' '2.8' '4.6' '1.5' 'Iris-versicolor']
 ['5.7' '2.8' '4.5' '1.3' 'Iris-versicolor']]
[['6.3' '3.3' '4.7' '1.6' 'Iris-versicolor']
 ['4.9' '2.4' '3.3' '1.0' 'Iris-versicolor']
 ['6.6' '2.9' '4.6' '1.3' 'Iris-versicolor']
 ['5.2' '2.7' '3.9' '1.4' 'Iris-versicolor']
 ['5.0' '2.0' '3.5' '1.0' 'Iris-versicolor']
 ['5.9' '3.0' '4.2' '1.5' 'Iris-versicolor']
 ['6.0' '2.2' '4.0' '1.0' 'Iris-versicolor']]
[['6.1' '2.9' '4.7' '1.4' 'Iris-versicolor']
 ['5.6' '2.9' '3.6' '1.3' 'Iris-versicolor']
 ['6.7' '3.1' '4.4' '1.4' 'Iris-versicolor']
 ['5.6' '3.0' '4.5' '1.5' 'Iris-versicolor']
 ['5.8' '2.7' '4.1' '1.0' 'Iris-versicolor']
 ['6.2' '2.2' '4.5' '1.5' 'Iris-versicolor']
 ['5.6' '2.5' '3.9' '1.1' 'Iris-versicolor']]
[['5.9' '3.2' '4.8' '1.8' 'Iris-versicolor']
 ['6.1' '2.8' '4.0' '1.3' 'Iris-versicolor']
 ['6.3' '2.5' '4.9' '1.5' 'Iris-versicolor']
 ['6.1' '2.8' '4.7' '1.2' 'Iris-versicolor']
 ['6.4' '2.9' '4.3' '1.3' 'Iris-versicolor']
 ['6.6' '3.0' '4.4' '1.4' 'Iris-versicolor']
 ['6.8' '2.8' '4.8' '1.4' 'Iris-versicolor']]
[['6.7' '3.0' '5.0' '1.7' 'Iris-versicolor']
 ['6.0' '2.9' '4.5' '1.5' 'Iris-versicolor']
 ['5.7' '2.6' '3.5' '1.0' 'Iris-versicolor']
 ['5.5' '2.4' '3.8' '1.1' 'Iris-versicolor']
 ['5.5' '2.4' '3.7' '1.0' 'Iris-versicolor']
 ['5.8' '2.7' '3.9' '1.2' 'Iris-versicolor']
 ['6.0' '2.7' '5.1' '1.6' 'Iris-versicolor']]
[['5.4' '3.0' '4.5' '1.5' 'Iris-versicolor']
 ['6.0' '3.4' '4.5' '1.6' 'Iris-versicolor']
 ['6.7' '3.1' '4.7' '1.5' 'Iris-versicolor']
 ['6.3' '2.3' '4.4' '1.3' 'Iris-versicolor']
 ['5.6' '3.0' '4.1' '1.3' 'Iris-versicolor']
 ['5.5' '2.5' '4.0' '1.3' 'Iris-versicolor']
 ['5.5' '2.6' '4.4' '1.2' 'Iris-versicolor']]
[['6.1' '3.0' '4.6' '1.4' 'Iris-versicolor']
 ['5.8' '2.6' '4.0' '1.2' 'Iris-versicolor']
 ['5.0' '2.3' '3.3' '1.0' 'Iris-versicolor']
 ['5.6' '2.7' '4.2' '1.3' 'Iris-versicolor']
 ['5.7' '3.0' '4.2' '1.2' 'Iris-versicolor']
 ['5.7' '2.9' '4.2' '1.3' 'Iris-versicolor']
 ['6.2' '2.9' '4.3' '1.3' 'Iris-versicolor']]
[['5.1' '2.5' '3.0' '1.1' 'Iris-versicolor']
 ['5.7' '2.8' '4.1' '1.3' 'Iris-versicolor']
 ['6.3' '3.3' '6.0' '2.5' 'Iris-virginica']
 ['5.8' '2.7' '5.1' '1.9' 'Iris-virginica']
 ['7.1' '3.0' '5.9' '2.1' 'Iris-virginica']
 ['6.3' '2.9' '5.6' '1.8' 'Iris-virginica']
 ['6.5' '3.0' '5.8' '2.2' 'Iris-virginica']]
[['7.6' '3.0' '6.6' '2.1' 'Iris-virginica']
 ['4.9' '2.5' '4.5' '1.7' 'Iris-virginica']
 ['7.3' '2.9' '6.3' '1.8' 'Iris-virginica']
 ['6.7' '2.5' '5.8' '1.8' 'Iris-virginica']
 ['7.2' '3.6' '6.1' '2.5' 'Iris-virginica']
 ['6.5' '3.2' '5.1' '2.0' 'Iris-virginica']
 ['6.4' '2.7' '5.3' '1.9' 'Iris-virginica']]
[['6.8' '3.0' '5.5' '2.1' 'Iris-virginica']
 ['5.7' '2.5' '5.0' '2.0' 'Iris-virginica']
 ['5.8' '2.8' '5.1' '2.4' 'Iris-virginica']
 ['6.4' '3.2' '5.3' '2.3' 'Iris-virginica']
 ['6.5' '3.0' '5.5' '1.8' 'Iris-virginica']
 ['7.7' '3.8' '6.7' '2.2' 'Iris-virginica']
 ['7.7' '2.6' '6.9' '2.3' 'Iris-virginica']]
[['6.0' '2.2' '5.0' '1.5' 'Iris-virginica']
 ['6.9' '3.2' '5.7' '2.3' 'Iris-virginica']
 ['5.6' '2.8' '4.9' '2.0' 'Iris-virginica']
 ['7.7' '2.8' '6.7' '2.0' 'Iris-virginica']
 ['6.3' '2.7' '4.9' '1.8' 'Iris-virginica']
 ['6.7' '3.3' '5.7' '2.1' 'Iris-virginica']
 ['7.2' '3.2' '6.0' '1.8' 'Iris-virginica']]
[['6.2' '2.8' '4.8' '1.8' 'Iris-virginica']
 ['6.1' '3.0' '4.9' '1.8' 'Iris-virginica']
 ['6.4' '2.8' '5.6' '2.1' 'Iris-virginica']
 ['7.2' '3.0' '5.8' '1.6' 'Iris-virginica']
 ['7.4' '2.8' '6.1' '1.9' 'Iris-virginica']
 ['7.9' '3.8' '6.4' '2.0' 'Iris-virginica']
 ['6.4' '2.8' '5.6' '2.2' 'Iris-virginica']]
[['6.3' '2.8' '5.1' '1.5' 'Iris-virginica']
 ['6.1' '2.6' '5.6' '1.4' 'Iris-virginica']
 ['7.7' '3.0' '6.1' '2.3' 'Iris-virginica']
 ['6.3' '3.4' '5.6' '2.4' 'Iris-virginica']
 ['6.4' '3.1' '5.5' '1.8' 'Iris-virginica']
 ['6.0' '3.0' '4.8' '1.8' 'Iris-virginica']
 ['6.9' '3.1' '5.4' '2.1' 'Iris-virginica']]
[['6.7' '3.1' '5.6' '2.4' 'Iris-virginica']
 ['6.9' '3.1' '5.1' '2.3' 'Iris-virginica']
 ['5.8' '2.7' '5.1' '1.9' 'Iris-virginica']
 ['6.8' '3.2' '5.9' '2.3' 'Iris-virginica']
 ['6.7' '3.3' '5.7' '2.5' 'Iris-virginica']
 ['6.7' '3.0' '5.2' '2.3' 'Iris-virginica']
 ['6.3' '2.5' '5.0' '1.9' 'Iris-virginica']]
[['6.5' '3.0' '5.2' '2.0' 'Iris-virginica']
 ['6.2' '3.4' '5.4' '2.3' 'Iris-virginica']
 ['5.9' '3.0' '5.1' '1.8' 'Iris-virginica']]

In [24]:
my_own_dataset=pd.DataFrame({'col1':range(5), 'col2' : [1.0]*5, 'col3' : 1.0,'col4':'Hello World'})
my_own_dataset

   col1  col2  col3         col4
0     0   1.0   1.0  Hello World
1     1   1.0   1.0  Hello World
2     2   1.0   1.0  Hello World
3     3   1.0   1.0  Hello World
4     4   1.0   1.0  Hello World

In [25]:
my_own_dataset.dtypes

col1      int64
col2    float64
col3    float64
col4     object
dtype: object

In [27]:
my_own_dataset['col1']=my_own_dataset['col1'].astype(float)
my_own_dataset.dtypes

col1    float64
col2    float64
col3    float64
col4     object
dtype: object

In [28]:
my_own_dataset

   col1  col2  col3         col4
0   0.0   1.0   1.0  Hello World
1   1.0   1.0   1.0  Hello World
2   2.0   1.0   1.0  Hello World
3   3.0   1.0   1.0  Hello World
4   4.0   1.0   1.0  Hello World

In [32]:
mask_feature = iris['sepal_length']>6
mask_feature

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
120     True
121    False
122     True
123     True
124     True
125     True
126     True
127     True
128     True
129     True
130     True
131     True
132     True
133     True
134     True
135     True
136     True
137     True
138    False
139     True
140     True
141     True
142    False
143     True
144     True
145     True
146     True
147     True
148     True
149    False
Name: sepal_length, Length: 150, dtype: bool

In [34]:
mask_target=iris['target']=='Iris-virginica'
mask_target

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
120     True
121     True
122     True
123     True
124     True
125     True
126     True
127     True
128     True
129     True
130     True
131     True
132     True
133     True
134     True
135     True
136     True
137     True
138     True
139     True
140     True
141     True
142     True
143     True
144     True
145     True
146     True
147     True
148     True
149     True
Name: target, Length: 150, dtype: bool

In [36]:
iris.loc[mask_target, 'target']='New label'
iris['target'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'New label'], dtype=object)

In [40]:
grouped_targets_mean=iris.groupby(['target']).mean()
grouped_targets_var=iris.groupby(['target']).var()
grouped_targets_sum=iris.groupby(['target']).sum()
grouped_targets_count=iris.groupby(['target']).count()
grouped_targets_mean, grouped_targets_var, grouped_targets_sum, grouped_targets_count

(                 sepal_length  sepal_width  petal_length  petal_width
 target
 Iris-setosa             5.006        3.418         1.464        0.244
 Iris-versicolor         5.936        2.770         4.260        1.326
 New label               6.588        2.974         5.552        2.026,
                  sepal_length  sepal_width  petal_length  petal_width
 target
 Iris-setosa          0.124249     0.145180      0.030106     0.011494
 Iris-versicolor      0.266433     0.098469      0.220816     0.039106
 New label            0.404343     0.104004      0.304588     0.075433,
                  sepal_length  sepal_width  petal_length  petal_width
 target
 Iris-setosa             250.3        170.9          73.2         12.2
 Iris-versicolor         296.8        138.5         213.0         66.3
 New label               329.4        148.7         277.6        101.3,
                  sepal_length  sepal_width  petal_length  petal_width
 target
 Iris-setosa                50           50            50           50
 Iris-versicolor            50           50            50           50
 New label                  50           50            50           50)

In [44]:
iris.sort_values(by='sepal_length')

     sepal_length  sepal_width  petal_length  petal_width           target
13            4.3          3.0           1.1          0.1      Iris-setosa
42            4.4          3.2           1.3          0.2      Iris-setosa
38            4.4          3.0           1.3          0.2      Iris-setosa
8             4.4          2.9           1.4          0.2      Iris-setosa
41            4.5          2.3           1.3          0.3      Iris-setosa
22            4.6          3.6           1.0          0.2      Iris-setosa
3             4.6          3.1           1.5          0.2      Iris-setosa
6             4.6          3.4           1.4          0.3      Iris-setosa
47            4.6          3.2           1.4          0.2      Iris-setosa
2             4.7          3.2           1.3          0.2      Iris-setosa
29            4.7          3.2           1.6          0.2      Iris-setosa
12            4.8          3.0           1.4          0.1      Iris-setosa
45            4.8          3.0           1.4          0.3      Iris-setosa
24            4.8          3.4           1.9          0.2      Iris-setosa
11            4.8          3.4           1.6          0.2      Iris-setosa
30            4.8          3.1           1.6          0.2      Iris-setosa
57            4.9          2.4           3.3          1.0  Iris-versicolor
106           4.9          2.5           4.5          1.7        New label
34            4.9          3.1           1.5          0.1      Iris-setosa
9             4.9          3.1           1.5          0.1      Iris-setosa
37            4.9          3.1           1.5          0.1      Iris-setosa
1             4.9          3.0           1.4          0.2      Iris-setosa
40            5.0          3.5           1.3          0.3      Iris-setosa
26            5.0          3.4           1.6          0.4      Iris-setosa
49            5.0          3.3           1.4          0.2      Iris-setosa
35            5.0          3.2           1.2          0.2      Iris-setosa
43            5.0          3.5           1.6          0.6      Iris-setosa
60            5.0          2.0           3.5          1.0  Iris-versicolor
7             5.0          3.4           1.5          0.2      Iris-setosa
93            5.0          2.3           3.3          1.0  Iris-versicolor
..            ...          ...           ...          ...              ...
58            6.6          2.9           4.6          1.3  Iris-versicolor
75            6.6          3.0           4.4          1.4  Iris-versicolor
86            6.7          3.1           4.7          1.5  Iris-versicolor
140           6.7          3.1           5.6          2.4        New label
108           6.7          2.5           5.8          1.8        New label
77            6.7          3.0           5.0          1.7  Iris-versicolor
65            6.7          3.1           4.4          1.4  Iris-versicolor
144           6.7          3.3           5.7          2.5        New label
145           6.7          3.0           5.2          2.3        New label
124           6.7          3.3           5.7          2.1        New label
143           6.8          3.2           5.9          2.3        New label
76            6.8          2.8           4.8          1.4  Iris-versicolor
112           6.8          3.0           5.5          2.1        New label
139           6.9          3.1           5.4          2.1        New label
141           6.9          3.1           5.1          2.3        New label
52            6.9          3.1           4.9          1.5  Iris-versicolor
120           6.9          3.2           5.7          2.3        New label
50            7.0          3.2           4.7          1.4  Iris-versicolor
102           7.1          3.0           5.9          2.1        New label
129           7.2          3.0           5.8          1.6        New label
125           7.2          3.2           6.0          1.8        New label
109           7.2          3.6           6.1          2.5        New label
107           7.3          2.9           6.3          1.8        New label
130           7.4          2.8           6.1          1.9        New label
105           7.6          3.0           6.6          2.1        New label
122           7.7          2.8           6.7          2.0        New label
118           7.7          2.6           6.9          2.3        New label
117           7.7          3.8           6.7          2.2        New label
135           7.7          3.0           6.1          2.3        New label
131           7.9          3.8           6.4          2.0        New label

[150 rows x 5 columns]

In [43]:
iris.sort_index(by='sepal_length').head()

C:\Users\la\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  """Entry point for launching an IPython kernel.

    sepal_length  sepal_width  petal_length  petal_width       target
13           4.3          3.0           1.1          0.1  Iris-setosa
42           4.4          3.2           1.3          0.2  Iris-setosa
38           4.4          3.0           1.3          0.2  Iris-setosa
8            4.4          2.9           1.4          0.2  Iris-setosa
41           4.5          2.3           1.3          0.3  Iris-setosa

In [48]:
iris.apply(np.count_nonzero, axis=1).head()

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [49]:
iris.apply(np.count_nonzero).head()

sepal_length    150
sepal_width     150
petal_length    150
petal_width     150
target          150
dtype: int64

In [57]:
iris.applymap(lambda el:len(str(el))).head()

   sepal_length  sepal_width  petal_length  petal_width  target
0             3            3             3            3      11
1             3            3             3            3      11
2             3            3             3            3      11
3             3            3             3            3      11
4             3            3             3            3      11

In [66]:
iris.apply(lambda el:str(el),axis=1).head()

0    sepal_length            5.1\nsepal_width      ...
1    sepal_length            4.9\nsepal_width      ...
2    sepal_length            4.7\nsepal_width      ...
3    sepal_length            4.6\nsepal_width      ...
4    sepal_length              5\nsepal_width      ...
dtype: object

In [65]:
iris.apply(lambda el:str(el),axis=0).head()

sepal_length    0      5.1\n1      4.9\n2      4.7\n3      4.6...
sepal_width     0      3.5\n1        3\n2      3.2\n3      3.1...
petal_length    0      1.4\n1      1.4\n2      1.3\n3      1.5...
petal_width     0      0.2\n1      0.2\n2      0.2\n3      0.2...
target          0      Iris-setosa\n1      Iris-setosa\n2     ...
dtype: object

In [67]:
iris.apply(lambda el:len(str(el)),axis=1).head()

0    162
1    162
2    162
3    162
4    162
dtype: int64